print(" Start....")
# print("")
a = float(input("Enter value of a: "))
b = float(input("Enter value of b: "))
print("Addition:",a + b)
print("Subtraction:",a - b)
print("Multiplication:",a * b)
print("Division:", a / b)
